# Generated by Django 2.0.6 on 2019-01-14 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('version', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaperlessVersion',
        ),
    ]
